### ISSUE TITLE
conflicting keybindings?

### ISSUE THREAD

**Issue by kronikpillow** [arcolinux/arcolinux-awesome#1]
there seem to be conflicting keybindings in rc.lua for awesome, or am I missing something? is there some special way to trigger them to behave separately?

awful.key({ modkey }, "c", ---- conky toggle & copy terminal to gtk
awful.key({ modkey }, "v", ---- pavucontrol & copy gtk to terminal
awful.key({ modkey }, "h", ---- htop & focus left
awful.key({ modkey }, "k"  ----- screenlock & focus down
awful.key({ modkey1, altkey   }, "w", ---- arcolinux-welcome-app & editorgui

I took the time and checked them all in rc.lua, I think the above conflicts sums it up

**Comment by arcolinuxz** [comment]
done
