### ISSUE TITLE
weather widget 

### ISSUE THREAD

**Issue by unforgivenvirtuoso** [arcolinux/arcolinux-awesome#4]
i have gotten the widget icon to show but it only says N/A and when i hover my mouse over it a question mark over the notifier box is there, with no information of the weather. I have copied code from this repo relating to weather but it hasnt seemed to fix it and bizarrely if i comment out all of the code relating to weather in my theme file it breaks my rc.lua. The theme im using is the multicolor one.

This is my first time on linux so apologies if i am being stupid 

thanks for the help <3

**Comment by arcolinuxz** [comment]
We have left it out from the standard look for a reason.
These things always break.
It is a never mind or whatever thing.
Do not use it.
There are apps that give yout the weather

`wttr antwerp`

xfce has one I believe

it has to do with the connection to 'a website" - service that get blocked or are made available if paid or are made available after create accounts and apis - not worth the trouble

so no it is not you
